version: "3"

services:
  bot:
    build:
      context: ..
      dockerfile: docker/bot/Dockerfile
    volumes:
      - ../config:/etc/endbot/config
    ports:
      - 34345:34345
    depends_on:
      - db
      - redis
    environment:
      ENV: "production"

  db:
    image: mysql
    command: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: enddb
      MYSQL_USER: endbot
      MYSQL_PASSWORD: supersecret

  redis:
    image: redis
    restart: always
