version: "3"

services:
  bot:
    container_name: bot
    build:
      context: ..
      dockerfile: ./docker/bot/Dockerfile
    volumes:
      - ../config:/etc/endbot/config
    ports:
      - 34345:34345
